config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'statics#index'
  resources :homes
  resources :games
  resources :ourmembers
  resources :ourexectives
  resources :inputs
  resources :timeouts
  resources :gamemembers
  resources :gameexectives

  get 'games/index/:id' => 'games#index',as:'games_index'

  get 'statics/index' => 'statics#index'
  get 'statics/about' => 'statics#about'
  get 'statics/score' => 'statics#score'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :input 
end

app/models/gameexective.rb
class Gameexective < ApplicationRecord
    belongs_to :input
end

app/models/gamemember.rb
class Gamemember < ApplicationRecord
    belongs_to :input
end

app/models/input.rb
class Input < ApplicationRecord
    belongs_to :user
    has_many :gamemembers
    has_many :gameexectives
    has_many :games
    has_many :time_outs
end

app/models/ourexective.rb
class Ourexective < ApplicationRecord
    belongs_to :user
end

app/models/ourmember.rb
class Ourmember < ApplicationRecord
    belongs_to :user
end

app/models/time_out.rb
class TimeOut < ApplicationRecord
    belongs_to :input
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :inputs, dependent: :destroy
  has_many :ourmembers, dependent: :destroy
  has_many :ourexectives, dependent: :destroy
  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
    def index
      @gamemembers = Gamemember.all
      @gameexectives = Gameexective.all
      @games = Game.all
      @timeouts = TimeOut.all
      @input_show = Input.find(params[:id])
      @gamemember = Gamemember.new
      @gameexective = Gameexective.new
      @game = Game.new
      @timeout = TimeOut.new
      @ourmembers = Ourmember.where(user_id: current_user.id)
      @ourexectives = Ourexective.where(user_id: current_user.id)
      

  
      end

    def create
      game = Game.new(game_params)
      game.save!
      redirect_to :action => "index", :id => game.input_id
    end

    def edit
      @game = Game.find(params[:game_id]) if params[:game_id]
      @timeout = TimeOut.find(params[:timeout_id]) if params[:timeout_id]
      @gamemember = Gamemember.find(params[:gamemember_id]) if params[:gamemember_id]
      @gameexective = Gameexective.find(params[:gameexective_id]) if params[:gameexective_id]
    end

    def update
      game = Game.find(params[:id])
      if game.update(game_params)
        redirect_to :action => "index", :id => game.input_id
      else
        redirect_to :action => "index"
      end
    end


    def destroy
      game = Game.find(params[:id])
      game.destroy
      redirect_to :action => "index", :id => game.input_id
    end


    private
    def game_params
      params.require(:game).permit(:our, :back_number, :time_minute, :time_second, :action, :half, :input_id)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
    @gamemembers = Gamemember.all
    @gameexectives = Gameexective.all
    @gamemember = Gamemember.new
    @gamemember = Gamemember.new
    @input_show = Input.all.where(user_id: current_user.id)
    @input = Input.new
  end


  def show
    @input = Input.find(params[:id])
    @gamemember = Gamemember.all.where(input_id: params[:id])
    @gameexective = Gameexective.all.where(input_id: params[:id])
    @game = Game.all.where(input_id: params[:id])
    @timeout = TimeOut.all.where(input_id: params[:id])


    games = Game.where(input_id: params[:id])
    a_game_members = Gamemember.where(input_id: params[:id]).where(our: "Aチーム")
    b_game_members = Gamemember.where(input_id: params[:id]).where(our: "Bチーム")
    @a_point = []
    @a_faul = []
    @a_two_minutes_faul = []
    @a_exit = []
    @b_point = []
    @b_faul = []
    @b_two_minutes_faul = []
    @b_exit = []
    a_game_members.each do |t| 
      @a_point << games.where(back_number: t.back_number).where(action: "得点").where(our:"Aチーム").count 
      @a_faul << games.where(back_number: t.back_number).where(action: "警告").where(our:"Aチーム").count
      @a_two_minutes_faul << games.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Aチーム").count
      @a_exit << games.where(back_number: t.back_number).where(action: "退場").where(our:"Aチーム").count
    end 
    b_game_members.each do |t| 
      @b_point << games.where(back_number: t.back_number).where(action: "得点").where(our:"Bチーム").count 
      @b_faul << games.where(back_number: t.back_number).where(action: "警告").where(our:"Bチーム").count
      @b_two_minutes_faul << games.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Bチーム").count
      @b_exit << games.where(back_number: t.back_number).where(action: "退場").where(our:"Bチーム").count
    end 
  end

  
  def edit
    @input = Input.find(params[:id])
  end
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
before_action :authenticate_user!
def create
    input = Input.new(input_params)
    input.user_id = current_user.id
     if input.save
       redirect_to homes_path
     else
       redirect_to homes_path
     end    
end

def edit
    @input = Input.find(params[:id])
end

def update
    input = Input.find(params[:id])
    if input.update(input_params)
      redirect_to homes_path, :id => input.id
    else
      redirect_to homes_path
    end
end

def destroy
    input = Input.find(params[:id])
    input.destroy
    redirect_to homes_path
end

private
def input_params
    params.require(:input).permit(:date, :place,:game_name,:game_round,:gender,:age)
end

end

app/controllers/ourmembers_controller.rb
class OurmembersController < ApplicationController
  before_action :authenticate_user!
  def index
    @ourmembers = Ourmember.all
    @ourexectives = Ourexective.all
    @ourmember = Ourmember.new
    @ourexective = Ourexective.new
  end


  def create
    ourmember = Ourmember.new(ourmember_params)
    ourmember.user_id = current_user.id
    if ourmember.save
      redirect_to action: "index"
    else
      redirect_to action: "index"
    end
  end


  def edit
    @ourmember = Ourmember.find(params[:ourmember_id]) if params[:ourmember_id] 
    @ourexective = Ourexective.find(params[:ourexective_id]) if params[:ourexective_id]
  end


  def update
    ourmember = Ourmember.find(params[:id])
    if ourmember.update(ourmember_params)
      redirect_to :action => "index", :id => ourmember.id
    else
      redirect_to :action => "index"
    end
  end


  def destroy
    ourmember = Ourmember.find(params[:id])
    ourmember.destroy
    redirect_to action: :index
  end


  private
  def ourmember_params
    params.require(:ourmember).permit(:name, :back_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/ourexectives_helper.rb
module OurexectivesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/timeouts_helper.rb
module TimeoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ourmembers/edit.html.erb
<%= stylesheet_link_tag 'ourmembers-edit', :media => "all" %>


<div class="container">
    <div class="row ">
        <div class="col">
            <ul class="sidenav">
                <li><a class="active" href="#top"><%= link_to 'トップページ', statics_index_path %></a></li>
                <li><a href="#handball"><%= link_to "ハンドボールとは？",statics_about_path %></a></li>
                <li><a href="#score"><%= link_to "スコアについて",statics_score_path %></a></li>
                <li><a href="#score-index"><%= link_to "スコア一覧",homes_path %></a></li>
                <li><a href="#member"><%= link_to "マイチームメンバー",ourmembers_path %></a></li>
            <ul>
        </div> 

        <div class="col-9">
            <% if @ourmember %>
                <h3>メンバー編集</h3>
                <div class="member-home">
                    <%= link_to "メンバー一覧に戻る",ourmembers_path, class:"btn btn-outline-primary" %>
                </div>
                <%= form_for(@ourmember, :url => { controller:'ourmembers', action:'update'})do |f| %>
                <div class="member">
                    <div class="member1">
                        <%= f.label :背番号 %>
                        <%= f.number_field :back_number, :size => 5 %> 
                        <%= f.label :メンバー氏名 %>
                        <%= f.text_field :name, :size => 30 %> 
                    </div>
                    <div class="member2">
                        <%= f.submit "編集する" %>
                    </div>
                </div>
                <% end %>
            <% end %>


            <% if @ourexective %>
                <h3>役員編集</h3>
                <div class="member-home">
                    <%= link_to "メンバー一覧に戻る",ourmembers_path %>
                </div>
                <%= form_for(@ourexective, :url => { controller:'ourexectives', action:'update'})do |f| %>
                <div class="member">
                    <div class="member1">
                        <%= f.label :役員ランク %>
                        <%= f.select :rank, 
                            [["役員A"],["役員B"],["役員C"],["役員D"]], include_blank: "選択して下さい" %>
                        <%= f.label :役員氏名 %>
                        <%= f.text_field :name, :size => 30 %> 
                    </div>
                    <div class="member2">
                        <%= f.submit "編集する" %>
                    </div>
                </div>
                <% end %>
            <% end %>
        </div>

    </div>
</div>  

app/views/ourmembers/index.html.erb
<%= stylesheet_link_tag 'ourmembers-index', :media => "all" %>


<div class="container">
    <div class="row ">
        <div class="col">
            <ul class="sidenav">
                <li><a class="active" href="#top"><%= link_to 'トップページ', statics_index_path %></a></li>
                <li><a href="#handball"><%= link_to "ハンドボールとは？",statics_about_path %></a></li>
                <li><a href="#score"><%= link_to "スコアについて",statics_score_path %></a></li>
                <li><a href="#score-index"><%= link_to "スコア一覧",homes_path %></a></li>
                <li><a href="#member"><%= link_to "マイチームメンバー",ourmembers_path %></a></li>
            <ul>
        </div> 


        <div class="col-9">
            <h3>メンバー</h3>
            <%= form_for(@ourmember, :url => { controller:'ourmembers', action:'create'})do |f| %>
            <div class="member">
                <div class="member1">
                    <%= f.label :メンバー背番号 %>
                    <div class="field">
                        <%= f.number_field :back_number%>
                    </div>
                    <%= f.label :メンバー氏名 %>
                    <div class="field">
                        <%= f.text_field :name,size: 30%>
                    </div>
                </div>
                <div class="member1-submit">
                    <%= f.submit "登録"%>
                </div>
            </div>
            <% end %>

            <%= form_for(@ourexective, :url => { controller:'ourexectives', action:'create'})do |f| %>
            <div class="member">
                <div class="member2">
                    <%= f.label :役員ランク %>
                    <div class="field">
                        <%= f.select :rank, 
                        [["役員A"],["役員B"],["役員C"],["役員D"]], include_blank: "選択して下さい" %>
                    </div>
                    <%= f.label :役員氏名 %>
                    <div class="field">
                        <%= f.text_field :name,size: 30%>
                    </div>
                </div>
                <div class="member2-submit">
                    <%= f.submit "登録"%>
                </div>
            </div>
            <% end %> 

            <h3>メンバー一覧</h3>
            <div class="row justify-content-center">
                <div class="col-md">
                    <h5>メンバー</h5>
                    <table border="1">
                        <tr>
                            <th>背番号</th>
                            <th>名前</th>
                            <th ></th>
                        </tr>
                        <% @ourmembers.each do |t| %>
                        <tr>
                            <td width="10%"><%= t.back_number %></td>
                            <td width="65%"><%= t.name %></td>
                            <td width="25%">
                                <%= link_to "編集", edit_ourmember_path(ourmember_id: t.id, id: t.id) %>
                                <%= link_to "削除", ourmember_path(t.id), method: :delete %>
                            </td>
                        </tr>
                        <% end %>
                    </table>
                </div>

                <div class="col-md">       
                    <h5>役員</h5>          
                    <table border="1">
                        <tr>
                            <th>ランク</th>
                            <th>名前</th>
                            <th></th>
                        </tr>
                            <% @ourexectives.each do |t| %>
                        <tr>
                            <td width="20%"><%= t.rank %></td>
                            <td width="55%"><%= t.name %></td>
                            <td width="25%">
                                <%= link_to "編集", edit_ourmember_path(ourexective_id: t.id, id: t.id) %>
                                <%= link_to "削除", ourexective_path(t.id), method: :delete %>
                            </td>
                        </tr>
                        <% end %>
                    </table>
                </div>
            </div>

        </div>
    </div>
</div>  