config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'statics#index'
  resources :homes
  resources :games
  resources :ourmembers
  resources :ourexectives
  resources :inputs
  resources :timeouts
  resources :gamemembers
  resources :gameexectives

  get 'games/index/:id' => 'games#index',as:'games_index'

  get 'statics/index' => 'statics#index'
  get 'statics/about' => 'statics#about'
  get 'statics/score' => 'statics#score'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :input 
end

app/models/gameexective.rb
class Gameexective < ApplicationRecord
    belongs_to :input
end

app/models/gamemember.rb
class Gamemember < ApplicationRecord
    belongs_to :input
end

app/models/input.rb
class Input < ApplicationRecord
    belongs_to :user
    has_many :gamemembers
    has_many :gameexectives
    has_many :games
    has_many :time_outs
end

app/models/ourexective.rb
class Ourexective < ApplicationRecord
    belongs_to :user
end

app/models/ourmember.rb
class Ourmember < ApplicationRecord
    belongs_to :user
end

app/models/time_out.rb
class TimeOut < ApplicationRecord
    belongs_to :input
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :inputs, dependent: :destroy
  has_many :ourmembers, dependent: :destroy
  has_many :ourexectives, dependent: :destroy
  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
    def index
      @gamemembers = Gamemember.all
      @gameexectives = Gameexective.all
      @games = Game.all
      @timeouts = TimeOut.all
      @input_show = Input.find(params[:id])
      @gamemember = Gamemember.new
      @gameexective = Gameexective.new
      @game = Game.new
      @timeout = TimeOut.new
      @ourmembers = Ourmember.where(user_id: current_user.id)
      @ourexectives = Ourexective.where(user_id: current_user.id)
      

  
      end

    def create
      game = Game.new(game_params)
      game.save!
      redirect_to :action => "index", :id => game.input_id
    end

    def edit
      @game = Game.find(params[:game_id]) if params[:game_id]
      @timeout = TimeOut.find(params[:timeout_id]) if params[:timeout_id]
      @gamemember = Gamemember.find(params[:gamemember_id]) if params[:gamemember_id]
      @gameexective = Gameexective.find(params[:gameexective_id]) if params[:gameexective_id]
    end

    def update
      game = Game.find(params[:id])
      if game.update(game_params)
        redirect_to :action => "index", :id => game.input_id
      else
        redirect_to :action => "index"
      end
    end


    def destroy
      game = Game.find(params[:id])
      game.destroy
      redirect_to :action => "index", :id => game.input_id
    end


    private
    def game_params
      params.require(:game).permit(:our, :back_number, :time_minute, :time_second, :action, :half, :input_id)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
    @gamemembers = Gamemember.all
    @gameexectives = Gameexective.all
    @gamemember = Gamemember.new
    @gamemember = Gamemember.new
    @input_show = Input.all.where(user_id: current_user.id)
    @input = Input.new
  end


  def show
    @input = Input.find(params[:id])
    @gamemember = Gamemember.all.where(input_id: params[:id])
    @gameexective = Gameexective.all.where(input_id: params[:id])
    @game = Game.all.where(input_id: params[:id])
    @timeout = TimeOut.all.where(input_id: params[:id])


    games = Game.where(input_id: params[:id])
    a_game_members = Gamemember.where(input_id: params[:id]).where(our: "Aチーム")
    b_game_members = Gamemember.where(input_id: params[:id]).where(our: "Bチーム")
    @a_point = []
    @a_faul = []
    @a_two_minutes_faul = []
    @a_exit = []
    @b_point = []
    @b_faul = []
    @b_two_minutes_faul = []
    @b_exit = []
    a_game_members.each do |t| 
      @a_point << games.where(back_number: t.back_number).where(action: "得点").where(our:"Aチーム").count 
      @a_faul << games.where(back_number: t.back_number).where(action: "警告").where(our:"Aチーム").count
      @a_two_minutes_faul << games.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Aチーム").count
      @a_exit << games.where(back_number: t.back_number).where(action: "退場").where(our:"Aチーム").count
    end 
    b_game_members.each do |t| 
      @b_point << games.where(back_number: t.back_number).where(action: "得点").where(our:"Bチーム").count 
      @b_faul << games.where(back_number: t.back_number).where(action: "警告").where(our:"Bチーム").count
      @b_two_minutes_faul << games.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Bチーム").count
      @b_exit << games.where(back_number: t.back_number).where(action: "退場").where(our:"Bチーム").count
    end 
  end

  
  def edit
    @input = Input.find(params[:id])
  end
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
before_action :authenticate_user!
def create
    input = Input.new(input_params)
    input.user_id = current_user.id
     if input.save
       redirect_to homes_path
     else
       redirect_to homes_path
     end    
end

def edit
    @input = Input.find(params[:id])
end

def update
    input = Input.find(params[:id])
    if input.update(input_params)
      redirect_to homes_path, :id => input.id
    else
      redirect_to homes_path
    end
end

def destroy
    input = Input.find(params[:id])
    input.destroy
    redirect_to homes_path
end

private
def input_params
    params.require(:input).permit(:date, :place,:game_name,:game_round,:gender,:age)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/members_second_helper.rb
module MembersSecondHelper
end

app/helpers/ourexectives_helper.rb
module OurexectivesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/timeouts_helper.rb
module TimeoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/edit.html.erb
<%= stylesheet_link_tag 'homes-edit', :media => "all" %>


<div class="container">
    <div class="row ">
        <div class="col">
            <ul class="sidenav">
                <li><a class="active" href="#top"><%= link_to 'トップページ', statics_index_path %></a></li>
                <li><a href="#handball"><%= link_to "ハンドボールとは？",statics_about_path %></a></li>
                <li><a href="#score"><%= link_to "スコアについて",statics_score_path %></a></li>
                <li><a href="#score-index"><%= link_to "スコア一覧",homes_path %></a></li>
                <li><a href="#member"><%= link_to "マイチームメンバー",ourmembers_path %></a></li>
            <ul>
        </div> 

        <div class="col-9">
            <h3>基本情報編集</h3>
            <div class="home-link">
                <%= link_to "スコア一覧に戻る",homes_path, class:"btn btn-outline-primary" %>
            </div>
            <%= form_for(@input, :url => { controller:'inputs', action:'update'})do |f| %>
            <div class="input">
                <div class="input1">
                    <%= f.label :日付 %>
                    <%= f.date_field :date, :size => 5 %> 

                    <%= f.label :場所 %>
                    <%= f.text_field :place, :size => 5 %> 

                    <%= f.label :大会名 %>
                    <%= f.text_field :game_name, :size => 5 %> 
                </div>
                <div class="input2">
                    <%= f.label :性別 %>
                    <%= f.select :gender, 
                    [["男"],["女"]], include_blank: "選択して下さい" %>

                    <%= f.label :回戦%>
                    <%= f.text_field :game_round, :size => 5 %> 

                    <%= f.label :種別 %>
                    <%= f.text_field :age, :size => 5 %> 
                </div>
                <div class="input3">
                    <%= f.submit "編集する" %>
                </div>
            </div>
            <% end %>
        </div>

    </div>
</div>  

app/views/homes/index.html.erb
<%= stylesheet_link_tag 'homes-index', :media => "all" %>

<div class="container">
    <div class="row ">
        <div class="col">
            <ul class="sidenav">
                <li><a class="active" href="#top"><%= link_to 'トップページ', statics_index_path %></a></li>
                <li><a href="#handball"><%= link_to "ハンドボールとは？",statics_about_path %></a></li>
                <li><a href="#score"><%= link_to "スコアについて",statics_score_path %></a></li>
                <li><a href="#score-index"><%= link_to "スコア一覧",homes_path %></a></li>
                <li><a href="#member"><%= link_to "マイチームメンバー",ourmembers_path %></a></li>
            <ul>
        </div> 

        <div class="col-9">
            <h3>ホーム</h3>
            <div class="input">
                <%= form_for(@input, :url => { controller:'inputs', action:'create'})do |f| %>
                <div class="input1">
                    <%= f.label :日付 %>
                        <div class="field">
                            <%= f.date_field :date,size: 15%>
                        </div>
                    <%= f.label :場所 %>
                        <div class="field">
                            <%= f.text_field :place,size: 15%>
                        </div>
                    <%= f.label :大会名 %>
                        <div class="field">
                            <%= f.text_field :game_name,size: 20%>
                        </div>
                </div>
                <div class="input2">
                    <%= f.label :性別 %>
                        <div class="field">
                            <%= f.select :gender, 
                            [["男"],["女"]], include_blank: "選択して下さい" %>
                        </div>
                    <%= f.label :回戦 %>
                        <div class="field">
                            <%= f.text_field :game_round,size: 15%>
                        </div>
                    <%= f.label :種別 %>
                        <div class="field">
                            <%= f.text_field :age,size: 15%>
                        </div>
                </div>
                <div class="input3">
                    <%= f.submit "登録"%>
                </div>
                <%end%>
            </div>


            <div class="home">
                <% @input_show.each do |t| %>
                <div class="card " style="max-width: 18rem;">
                    <div class="card-header">
                        <div class="card-header-name">スコア</div>
                        <div class="delete-button"><%= link_to "削除", input_path(t.id), method: :delete, class:"btn btn-danger"%></div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= t.date %>
                            <%= t.place %>
                            <%= t.game_name %>
                            <%= t.game_round %>
                            <%= t.gender %>
                            <%= t.age %>
                        </h5>
                        <p class="card-text">
                            <div class="game-button">
                                <%= link_to "試合経過作成", games_index_path(t.id), class:"btn btn-primary" %>  
                            </div>
                            <div class="edit-home-button">
                                <%= link_to "スコア詳細", home_path(t.id), class:"btn btn-outline-primary" %>
                                <%= link_to "編集する", edit_home_path(t.id), class:"btn btn-outline-primary"%>
                            </div>
                        </p>
                    </div>
                </div>
                <% end %>
            </div>

        </div>

    </div>
</div>  

app/views/homes/show.html.erb
<%= stylesheet_link_tag "homes-show", :media => "all" %>


<div class="container">
    <div class="row ">
        <div class="col">
            <ul class="sidenav">
                <li><a class="active" href="#top"><%= link_to 'トップページ', statics_index_path %></a></li>
                <li><a href="#handball"><%= link_to "ハンドボールとは？",statics_about_path %></a></li>
                <li><a href="#score"><%= link_to "スコアについて",statics_score_path %></a></li>
                <li><a href="#score-index"><%= link_to "スコア一覧",homes_path %></a></li>
                <li><a href="#member"><%= link_to "マイチームメンバー",ourmembers_path %></a></li>
            <ul>
        </div> 

        <div class="col-9">
            <h3>スコア詳細</h3>
            <div class="input">
                <div class="input1">
                    <%= link_to "スコア一覧に戻る",homes_path, class:"btn btn-outline-primary" %>
                </div>
                
                
                <div class="input2">
                    <h5>試合基本情報</h5>
                    <%= @input.date %>
                    <%= @input.place %>
                    <%= @input.game_name %>
                    <%= @input.game_round %>
                    <%= @input.gender %>
                    <%= @input.age %>
                </div>


            </div>
            
            <div class="row justify-content-around">
                <div class="col-5"> 
                    <div class="member">
                        <h5>メンバー</h5>
                        <h7>Aチーム</h7>
                        <table class="gamemember-table" border="1" width="100%">
                            <tr>
                                <th>背番号</th>
                                <th>名前</th>
                                <th>前半</th>
                                <th>後半</th>
                                <th>警告</th>
                                <th>退場</th>
                                <th>失格</th>
                            </tr>
                            <% @gamemember.where(our: "Aチーム").each do |t| %>
                            <tr>
                                <td width="10%"><%= t.back_number %></td>
                                <td style="width:100px;"><%= t.name%></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "得点").where(our:"Aチーム").where(half: "前半").count %></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "得点").where(our:"Aチーム").where(half: "後半").count %></td>
                                <td> <%= @game.where(back_number: t.back_number).where(action: "警告").where(our:"Aチーム").count %></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Aチーム").count %></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "失格").where(our:"Aチーム").count %></td>
                            </tr>
                            <% end %>
                        </table>

                        <h7>Bチーム</h7>
                        <table class="gamemember-table" border="1" width="100%">
                            <tr>
                                <th>背番号</th>
                                <th>名前</th>
                                <th>前半</th>
                                <th>後半</th>
                                <th>警告</th>
                                <th>退場</th>
                                <th>失格</th>
                            </tr>
                            <% @gamemember.where(our: "Bチーム").each do |t| %>
                            <tr>
                                <td width="10%"><%= t.back_number %></td>
                                <td style="width:100px;"><%= t.name%></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "得点").where(our:"Bチーム").where(half: "前半").count %></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "得点").where(our:"Bチーム").where(half: "後半").count %></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "警告").where(our:"Bチーム").count %></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Bチーム").count %></td>
                                <td><%= @game.where(back_number: t.back_number).where(action: "失格").where(our:"Bチーム").count %></td>
                            </tr>
                            <% end %>
                        </table>
                        

                        <h5>役員</h5>
                        <h7>Aチーム</h7>
                        <table class="gameexective-table" border="1" width="100%">
                            <tr>
                            <th>ランク</th>
                            <th>名前</th>
                            </tr>
                            <% @gameexective.where(our: "Aチーム").each do |t| %>
                            <tr>
                            <td width="25%"><%= t.rank %> </td>
                            <td width="60%"><%= t.name%></td>
                            </tr>
                            <% end %>
                        </table>              
                        <h7>Bチーム</h7>
                        <table class="gameexective-table" border="1" width="100%">
                            <tr>
                                <th >ランク</th>
                                <th>名前</th>
                            </tr>
                            <% @gameexective.where(our: "Bチーム").each do |t| %>
                            <tr>
                                <td width="25%"><%= t.rank %> </td>
                                <td width="60%"><%= t.name%></td>
                            </tr>
                            <% end %>
                        </table>                 
                    </div>
                </div>



                <div class="col-5">
                <h5>スコア経過</h5>
                <h7>前半</h7>
                <table class="score-table" border="1" width="100%">
                    <tr>
                    <th>番号</th>
                    <th>結果</th>
                    <th>得点</th>
                    <th>時間</th>
                    <th>得点</th>
                    <th>結果</th>
                    <th>番号</th>
                    </tr>
                    
                    <% a_point = 0 %>
                    <% b_point = 0 %>
                    <% @game.order("time_minute asc").where(half: "前半").each do |t| %>
                        <% if t.our =="Aチーム"%>
                        <tr>
                            <td width="10%"><%= t.back_number %></td>
                            <td width="20%"><%= t.action %></td>
                            <td width="10%">
                                <% if t.action == "得点" and t.our=="Aチーム" %> 
                                <% a_point += 1 %>
                                <%= a_point %>
                                <% end %>
                            </td>
                            <td width="20%"><%= t.time_minute %>:<%= t.time_second %></td>
                            <td width="10%"></td>
                            <td width="20%"></td>
                            <td width="10%"></td>
                        </tr>
                        <% end %>

                        <% if t.our=="Bチーム"%>
                        <tr>
                            <td width="10%"></td>
                            <td width="20%"></td>
                            <td width="10%"></td>
                            <td width="20%"><%= t.time_minute %>:<%= t.time_second %></td>
                            <td width="10%" >
                                <% if t.action == "得点" %> 
                                <% b_point += 1 %>
                                <%= b_point %>
                                <% end %>
                            </td>
                            <td width="20%"><%= t.action %></td>
                            <td width="10%"><%= t.back_number %></td>
                        </tr>
                        <% end %>
                    <% end %>
                </table>


                <h7>後半</h7>
                <table class="score-table" border="1" width="100%">
                    <tr>
                        <th>番号</th>
                        <th>結果</th>
                        <th>得点</th>
                        <th>時間</th>
                        <th>得点</th>
                        <th>結果</th>
                        <th>番号</th>
                    </tr>
                    
                    <% @game.order("time_minute asc").where(half: "後半").each do |t| %>
                        <% if t.our =="Aチーム"%>
                        <tr>
                            <td width="10%"><%= t.back_number %></td>
                            <td width="20%"><%= t.action %></td>
                            <td width="10%">
                                <% if t.action == "得点" %> 
                                <% a_point += 1 %>
                                <%= a_point %>
                                <% end %>
                            </td>
                            <td width="20%"><%= t.time_minute %>:<%= t.time_second %></td>
                            <td width="10%"></td>
                            <td width="20%"></td>
                            <td width="10%"></td>
                        </tr>
                        <% end %>

                        <% if t.our=="Bチーム"%>
                        <tr>
                            <td width="10%"></td>
                            <td width="20%"></td>
                            <td width="10%"></td>
                            <td width="20%"><%= t.time_minute %>:<%= t.time_second %></td>
                            <td width="10%">
                                <% if t.action == "得点" %> 
                                <% b_point += 1 %>
                                <%= b_point %>
                                <% end %>
                            </td>
                            <td width="20%"><%= t.action %></td>
                            <td width="10%"><%= t.back_number %></td>
                        </tr>
                        <% end %>
                    <% end %>
                </table>



                <h7>得点集計</h7>
                <table border="1" width="100%">
                    <tr>
                        <th>合計</th>
                        <th>合計</th>
                    </tr>
                    <tr>
                        <th><%= @game.where(action: "得点").where(our: "Aチーム").count %></th>
                        <th><%= @game.where(action: "得点").where(our: "Bチーム").count %></th>
                    </tr>
                </table>
                
                




                    
                    <h5>タイムアウト</h5>
                    <h7>Aチーム</h7>
                    <div class="timeoutA-table">
                        <table class="timeoutA-table1" border="1" width="100%">
                        <tr>
                            <th style="height:20px;">前半</th>
                        </tr>
                        <% @timeout.order("time_minute asc").where(our: "Aチーム", half:"前半").each do |t| %>
                        <tr>
                            <td><%= t.time_minute %>:<%= t.time_second %></td>
                        </tr>
                        <% end %>
                        </table>

                        <table class="timeoutA-table2" border="1" width="100%">
                        <tr>
                            <th style="height:20px;">後半</th>
                        </tr>
                        <% @timeout.order("time_minute asc").where(our: "Aチーム",half:"後半").each do |t| %>
                        <tr>
                            <td><%= t.time_minute %>:<%= t.time_second %></td>
                        </tr>
                        <% end %>
                        </table>
                    </div>
                    

                    <h7>Bチーム</h7>
                    <div class="timeoutB-table">
                        <table class="timeoutB-table1" border="1" width="100%">
                        <tr>
                            <th style="height:20px;">前半</th>
                        </tr>
                        <% @timeout.order("time_minute asc").where(our: "Bチーム", half:"前半").each do |t| %>
                        <tr>
                            <td><%= t.time_minute %>:<%= t.time_second %></td>
                        </tr>
                        <% end %>
                        </table>

                        <table class="timeoutB-table2" border="1" width="100%">
                        <tr>
                            <th style="height:20px;">後半</th>
                        </tr>
                        <% @timeout.order("time_minute asc").where(our: "Bチーム",half:"後半").each do |t| %>
                        <tr>
                            <td><%= t.time_minute %>:<%= t.time_second %></td>
                        </tr>
                        <% end %>
                        </table>
                    </div>


                </div>


            </div>


        </div>

    </div>
</div>  









    
    

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>