config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'statics#index'
  resources :homes
  resources :games
  resources :ourmembers
  resources :ourexectives
  resources :inputs
  resources :timeouts
  resources :gamemembers
  resources :gameexectives

  get 'games/index/:id' => 'games#index',as:'games_index'

  get 'statics/index' => 'statics#index'
  get 'statics/about' => 'statics#about'
  get 'statics/score' => 'statics#score'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :input 
end

app/models/gameexective.rb
class Gameexective < ApplicationRecord
    belongs_to :input
end

app/models/gamemember.rb
class Gamemember < ApplicationRecord
    belongs_to :input
end

app/models/input.rb
class Input < ApplicationRecord
    belongs_to :user
    has_many :gamemembers
    has_many :gameexectives
    has_many :games
    has_many :time_outs
end

app/models/ourexective.rb
class Ourexective < ApplicationRecord
    belongs_to :user
end

app/models/ourmember.rb
class Ourmember < ApplicationRecord
    belongs_to :user
end

app/models/time_out.rb
class TimeOut < ApplicationRecord
    belongs_to :input
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :inputs, dependent: :destroy
  has_many :ourmembers, dependent: :destroy
  has_many :ourexectives, dependent: :destroy
  

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
    def index
      @gamemembers = Gamemember.all
      @gameexectives = Gameexective.all
      @games = Game.all
      @timeouts = TimeOut.all
      @input_show = Input.find(params[:id])
      @gamemember = Gamemember.new
      @gameexective = Gameexective.new
      @game = Game.new
      @timeout = TimeOut.new
      @ourmembers = Ourmember.where(user_id: current_user.id)
      @ourexectives = Ourexective.where(user_id: current_user.id)
      

  
      end

    def create
      game = Game.new(game_params)
      game.save!
      redirect_to :action => "index", :id => game.input_id
    end

    def edit
      @game = Game.find(params[:game_id]) if params[:game_id]
      @timeout = TimeOut.find(params[:timeout_id]) if params[:timeout_id]
      @gamemember = Gamemember.find(params[:gamemember_id]) if params[:gamemember_id]
      @gameexective = Gameexective.find(params[:gameexective_id]) if params[:gameexective_id]
    end

    def update
      game = Game.find(params[:id])
      if game.update(game_params)
        redirect_to :action => "index", :id => game.input_id
      else
        redirect_to :action => "index"
      end
    end


    def destroy
      game = Game.find(params[:id])
      game.destroy
      redirect_to :action => "index", :id => game.input_id
    end


    private
    def game_params
      params.require(:game).permit(:our, :back_number, :time_minute, :time_second, :action, :half, :input_id)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
    @gamemembers = Gamemember.all
    @gameexectives = Gameexective.all
    @gamemember = Gamemember.new
    @gamemember = Gamemember.new
    @input_show = Input.all.where(user_id: current_user.id)
    @input = Input.new
  end


  def show
    @input = Input.find(params[:id])
    @gamemember = Gamemember.all.where(input_id: params[:id])
    @gameexective = Gameexective.all.where(input_id: params[:id])
    @game = Game.all.where(input_id: params[:id])
    @timeout = TimeOut.all.where(input_id: params[:id])


    games = Game.where(input_id: params[:id])
    a_game_members = Gamemember.where(input_id: params[:id]).where(our: "Aチーム")
    b_game_members = Gamemember.where(input_id: params[:id]).where(our: "Bチーム")
    @a_point = []
    @a_faul = []
    @a_two_minutes_faul = []
    @a_exit = []
    @b_point = []
    @b_faul = []
    @b_two_minutes_faul = []
    @b_exit = []
    a_game_members.each do |t| 
      @a_point << games.where(back_number: t.back_number).where(action: "得点").where(our:"Aチーム").count 
      @a_faul << games.where(back_number: t.back_number).where(action: "警告").where(our:"Aチーム").count
      @a_two_minutes_faul << games.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Aチーム").count
      @a_exit << games.where(back_number: t.back_number).where(action: "退場").where(our:"Aチーム").count
    end 
    b_game_members.each do |t| 
      @b_point << games.where(back_number: t.back_number).where(action: "得点").where(our:"Bチーム").count 
      @b_faul << games.where(back_number: t.back_number).where(action: "警告").where(our:"Bチーム").count
      @b_two_minutes_faul << games.where(back_number: t.back_number).where(action: "2分間退場").where(our:"Bチーム").count
      @b_exit << games.where(back_number: t.back_number).where(action: "退場").where(our:"Bチーム").count
    end 
  end

  
  def edit
    @input = Input.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/ourexectives_helper.rb
module OurexectivesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/timeouts_helper.rb
module TimeoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Handball</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-list">
      <ul>
        <li><%= link_to "ログイン", homes_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= link_to "ログアウト",destroy_user_session_path %></li>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>